// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gqlgen

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetPublicUserPublicUserUser_public_view includes the requested fields of the GraphQL type user_public_view.
// The GraphQL type's documentation follows.
//
// columns and relationships of "user_public_view"
type GetPublicUserPublicUserUser_public_view struct {
	Login             string `json:"login"`
	GithubId          int    `json:"githubId"`
	CanAccessPlatform bool   `json:"canAccessPlatform"`
	CanBeAuditor      bool   `json:"canBeAuditor"`
	Campus            string `json:"campus"`
	// An array relationship
	PiscineGo []GetPublicUserPublicUserUser_public_viewPiscineGoEvent_user `json:"piscineGo"`
	// An array relationship
	Module []GetPublicUserPublicUserUser_public_viewModuleEvent_user `json:"module"`
}

// GetLogin returns GetPublicUserPublicUserUser_public_view.Login, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_view) GetLogin() string { return v.Login }

// GetGithubId returns GetPublicUserPublicUserUser_public_view.GithubId, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_view) GetGithubId() int { return v.GithubId }

// GetCanAccessPlatform returns GetPublicUserPublicUserUser_public_view.CanAccessPlatform, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_view) GetCanAccessPlatform() bool {
	return v.CanAccessPlatform
}

// GetCanBeAuditor returns GetPublicUserPublicUserUser_public_view.CanBeAuditor, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_view) GetCanBeAuditor() bool { return v.CanBeAuditor }

// GetCampus returns GetPublicUserPublicUserUser_public_view.Campus, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_view) GetCampus() string { return v.Campus }

// GetPiscineGo returns GetPublicUserPublicUserUser_public_view.PiscineGo, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_view) GetPiscineGo() []GetPublicUserPublicUserUser_public_viewPiscineGoEvent_user {
	return v.PiscineGo
}

// GetModule returns GetPublicUserPublicUserUser_public_view.Module, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_view) GetModule() []GetPublicUserPublicUserUser_public_viewModuleEvent_user {
	return v.Module
}

// GetPublicUserPublicUserUser_public_viewModuleEvent_user includes the requested fields of the GraphQL type event_user.
// The GraphQL type's documentation follows.
//
// columns and relationships of "event_user"
type GetPublicUserPublicUserUser_public_viewModuleEvent_user struct {
	Id int `json:"id"`
}

// GetId returns GetPublicUserPublicUserUser_public_viewModuleEvent_user.Id, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_viewModuleEvent_user) GetId() int { return v.Id }

// GetPublicUserPublicUserUser_public_viewPiscineGoEvent_user includes the requested fields of the GraphQL type event_user.
// The GraphQL type's documentation follows.
//
// columns and relationships of "event_user"
type GetPublicUserPublicUserUser_public_viewPiscineGoEvent_user struct {
	Id int `json:"id"`
}

// GetId returns GetPublicUserPublicUserUser_public_viewPiscineGoEvent_user.Id, and is useful for accessing the field via an interface.
func (v *GetPublicUserPublicUserUser_public_viewPiscineGoEvent_user) GetId() int { return v.Id }

// GetPublicUserResponse is returned by GetPublicUser on success.
type GetPublicUserResponse struct {
	// fetch data from the table: "user_public_view"
	PublicUser []GetPublicUserPublicUserUser_public_view `json:"publicUser"`
}

// GetPublicUser returns GetPublicUserResponse.PublicUser, and is useful for accessing the field via an interface.
func (v *GetPublicUserResponse) GetPublicUser() []GetPublicUserPublicUserUser_public_view {
	return v.PublicUser
}

// __GetPublicUserInput is used internally by genqlient
type __GetPublicUserInput struct {
	GithubId int `json:"githubId"`
}

// GetGithubId returns __GetPublicUserInput.GithubId, and is useful for accessing the field via an interface.
func (v *__GetPublicUserInput) GetGithubId() int { return v.GithubId }

// The query executed by GetPublicUser.
const GetPublicUser_Operation = `
query GetPublicUser ($githubId: Int) {
	publicUser: user_public_view(where: {githubId:{_eq:$githubId}}) {
		login
		githubId
		canAccessPlatform
		canBeAuditor
		campus
		piscineGo: events(where: {event:{path:{_like:"%piscine-go%"}}}, limit: 1) {
			id
		}
		module: events(where: {eventId:{_eq:41}}) {
			id
		}
	}
}
`

func GetPublicUser(
	ctx_ context.Context,
	client_ graphql.Client,
	githubId int,
) (data_ *GetPublicUserResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetPublicUser",
		Query:  GetPublicUser_Operation,
		Variables: &__GetPublicUserInput{
			GithubId: githubId,
		},
	}

	data_ = &GetPublicUserResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
